### PR TITLE
531 add built in round support to the dfr3 evaluator

### PR DESCRIPTION
**Pull request by longshuicy**
- I added a bunch more built-in math related functions just in case.
- Previously it didn't catch the round not supported nan, fixed that

---
To test, please run the pytest `tests/pyincore/models/test_dfr3curve.py` 
```
def test_fragility_eval()
...
```

### CODE REVIEW

**Comment by navarroc** [comment]
Looks good. There are a few pep8 errors about adding an extra line between functions. Can you fix those?

**Comment by longshuicy** [comment]
> Looks good. There are a few pep8 errors about adding an extra line between functions. Can you fix those?

Which file do you see the pep8 error? for some reason my IDE doesn't prompt me with those anymore. :-(

**Comment by navarroc** [comment]
> > Looks good. There are a few pep8 errors about adding an extra line between functions. Can you fix those?
> 
> Which file do you see the pep8 error? for some reason my IDE doesn't prompt me with those anymore. :-(

Sorry, I should have been more clear. In the test_dfr3curve.py class. My IDE complains about needing an extra blank line for a few of the test methods.

**Comment by longshuicy** [comment]
> > > Looks good. There are a few pep8 errors about adding an extra line between functions. Can you fix those?
> > 
> > 
> > Which file do you see the pep8 error? for some reason my IDE doesn't prompt me with those anymore. :-(
> 
> Sorry, I should have been more clear. In the test_dfr3curve.py class. My IDE complains about needing an extra blank line for a few of the test methods.

Ah i see them now. Thanks!
Fixed :-)

**Review by navarroc — APPROVED** [review]

**Review by jonglee1 — APPROVED** [review]

**Pull request merged**
