### PR TITLE
need to preserve original functions docstring

### PR DESCRIPTION
**Pull request by longshuicy**
Some of the method wrapped with custom decorators didn't build successfully with sphinx autodoc. Now add code to fix that.

---

To test:
- docker build -f Dockerfile -t doc/pyincore:customdecorator .
- docker run -ti --rm -p 8000:80 doc/pyincore:customdecorator
- Go to http://localhost:8000/doc/pyincore/
- Compare currently deployed docs vs local ones
e.g.
http://localhost:8000/doc/pyincore/modules.html#dfr3service.Dfr3Service.search_dfr3_sets --> show up correctly &#9989;
https://incore.ncsa.illinois.edu/doc/pyincore/modules.html#dfr3service.Dfr3Service.search_dfr3_sets Doesn't exist on production &#10060;

### CODE REVIEW

**Review by navarroc — APPROVED** [review]
Good catch, built the image and tested. Looks to be working now.

**Comment by ylyangtw** [comment]
Not sure whether it's my local but I am getting errors for this command `docker build -f Dockerfile -t doc/pyincore:customdecorator .`
Here is the output:
```
 => ERROR [builder 4/7] RUN micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt                                                                                   15.5s
------
 > [builder 4/7] RUN micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt:
#0 15.41 error    libmamba Could not solve for environment specs
#0 15.41     The following package could not be installed
#0 15.41     └─ pyomo >=6.0.0,<=6.6.2  does not exist (perhaps a typo or a missing channel).
#0 15.45 critical libmamba Could not solve for environment specs
------
Dockerfile:13
--------------------
  12 |     ENV PATH "$MAMBA_ROOT_PREFIX/bin:$PATH"
  13 | >>> RUN micromamba install -y -n base -c conda-forge \
  14 | >>>     beautifulsoup4 \
  15 | >>>     sphinx sphinx_rtd_theme \
  16 | >>>     -f requirements.txt
  17 |     
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt" did not complete successfully: exit code: 1
```

**Comment by ylyangtw** [comment]
> Not sure whether it's my local but I am getting errors for this command `docker build -f Dockerfile -t doc/pyincore:customdecorator .` Here is the output:
> 
> ```
>  => ERROR [builder 4/7] RUN micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt                                                                                   15.5s
> ------
>  > [builder 4/7] RUN micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt:
> #0 15.41 error    libmamba Could not solve for environment specs
> #0 15.41     The following package could not be installed
> #0 15.41     └─ pyomo >=6.0.0,<=6.6.2  does not exist (perhaps a typo or a missing channel).
> #0 15.45 critical libmamba Could not solve for environment specs
> ------
> Dockerfile:13
> --------------------
>   12 |     ENV PATH "$MAMBA_ROOT_PREFIX/bin:$PATH"
>   13 | >>> RUN micromamba install -y -n base -c conda-forge \
>   14 | >>>     beautifulsoup4 \
>   15 | >>>     sphinx sphinx_rtd_theme \
>   16 | >>>     -f requirements.txt
>   17 |     
> --------------------
> ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt" did not complete successfully: exit code: 1
> ```

my micromamba version 1.5.8

**Comment by navarroc** [comment]
> > Not sure whether it's my local but I am getting errors for this command `docker build -f Dockerfile -t doc/pyincore:customdecorator .` Here is the output:
> > ```
> >  => ERROR [builder 4/7] RUN micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt                                                                                   15.5s
> > ------
> >  > [builder 4/7] RUN micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt:
> > #0 15.41 error    libmamba Could not solve for environment specs
> > #0 15.41     The following package could not be installed
> > #0 15.41     └─ pyomo >=6.0.0,<=6.6.2  does not exist (perhaps a typo or a missing channel).
> > #0 15.45 critical libmamba Could not solve for environment specs
> > ------
> > Dockerfile:13
> > --------------------
> >   12 |     ENV PATH "$MAMBA_ROOT_PREFIX/bin:$PATH"
> >   13 | >>> RUN micromamba install -y -n base -c conda-forge \
> >   14 | >>>     beautifulsoup4 \
> >   15 | >>>     sphinx sphinx_rtd_theme \
> >   16 | >>>     -f requirements.txt
> >   17 |     
> > --------------------
> > ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt" did not complete successfully: exit code: 1
> > ```
> 
> my micromamba version 1.5.8

hmmm...it builds ok on my system. Your micromamba version shouldn't matter since this is building in docker not using your system settings.

**Comment by ylyangtw** [comment]
> > > Not sure whether it's my local but I am getting errors for this command `docker build -f Dockerfile -t doc/pyincore:customdecorator .` Here is the output:
> > > ```
> > >  => ERROR [builder 4/7] RUN micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt                                                                                   15.5s
> > > ------
> > >  > [builder 4/7] RUN micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt:
> > > #0 15.41 error    libmamba Could not solve for environment specs
> > > #0 15.41     The following package could not be installed
> > > #0 15.41     └─ pyomo >=6.0.0,<=6.6.2  does not exist (perhaps a typo or a missing channel).
> > > #0 15.45 critical libmamba Could not solve for environment specs
> > > ------
> > > Dockerfile:13
> > > --------------------
> > >   12 |     ENV PATH "$MAMBA_ROOT_PREFIX/bin:$PATH"
> > >   13 | >>> RUN micromamba install -y -n base -c conda-forge \
> > >   14 | >>>     beautifulsoup4 \
> > >   15 | >>>     sphinx sphinx_rtd_theme \
> > >   16 | >>>     -f requirements.txt
> > >   17 |     
> > > --------------------
> > > ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -c conda-forge     beautifulsoup4     sphinx sphinx_rtd_theme     -f requirements.txt" did not complete successfully: exit code: 1
> > > ```
> > 
> > 
> > my micromamba version 1.5.8
> 
> hmmm...it builds ok on my system. I just tested it again on mine. Your micromamba version shouldn't matter since this is building in docker not using your system settings.

No worries I got it run by adding `--platform linux/amd64` to the command. Will continue the testing

**Review by ylyangtw — APPROVED** [review]
Container ran ok. Compared several analyses between local and production, all are identical. Approving~

**Pull request merged**
