### PR TITLE
463 fix nci functionality

### PR DESCRIPTION
**Pull request by ylyangtw**
For testing, you can run 
```
python tests/pyincore/analyses/ncifunctionality/test_ncifunctionality.py
```

### CODE REVIEW

**Review by longshuicy — APPROVED** [review]
Looks good. Tested with the notebook as well.

**Comment by navarroc** [comment]
Can you remove the unused import "from numpy.linalg import inv"?

**Comment by longshuicy** [comment]
oh since you are already modifying this file, could you remove the redundant line here? https://github.com/IN-CORE/pyincore/pull/465/files#diff-f528b28bb8f6687d39ab711c9563ddacc0b95b09f16f02e3586d3a5948062d4bR132

**Comment by longshuicy** [comment]
Also line i think it should merge back with `df_functionality_nodes` instead of `epf_network_nodes`
https://github.com/IN-CORE/pyincore/pull/465/files#diff-f528b28bb8f6687d39ab711c9563ddacc0b95b09f16f02e3586d3a5948062d4bL146

it might be a bug

**Comment by ylyangtw** [comment]
> Can you remove the unused import "from numpy.linalg import inv"?

No problem. Removed

**Comment by ylyangtw** [comment]
> oh since you are already modifying this file, could you remove the redundant line here? https://github.com/IN-CORE/pyincore/pull/465/files#diff-f528b28bb8f6687d39ab711c9563ddacc0b95b09f16f02e3586d3a5948062d4bR132

OK, removed!

**Review by navarroc — APPROVED** [review]

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
