### PR TITLE
Conda

### PR DESCRIPTION
**Pull request by robkooper**
redo of #121 based on current release branch.

### CODE REVIEW

**Comment by ywkim312** [comment]
Does this publish to conda channel? I only see the building conda package. Anyway, it is great that it built the package finally.

**Comment by robkooper** [comment]
yes it does push at the step [Upload conda package](https://github.com/IN-CORE/pyincore/pull/163/files#diff-afc6e983051bc17a5c23667cd738c392226420d181ef22f6931b59215e3e4402R70) using `anacondo upload`.

**Comment by ywkim312** [comment]
> yes it does push at the step [Upload conda package](https://github.com/IN-CORE/pyincore/pull/163/files#diff-afc6e983051bc17a5c23667cd738c392226420d181ef22f6931b59215e3e4402R70) using `anacondo upload`.

But I don't see it in conda channel https://anaconda.org/IN-CORE/pyincore/files and also github action's upload part also greyed out.

**Comment by robkooper** [comment]
for testing i pushed it to kooper channel:
- https://github.com/IN-CORE/pyincore/releases/tag/v1.5.1rc1
- https://anaconda.org/kooper/pyincore/files
- https://test.pypi.org/project/pyincore/1.5.1rc1/

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
