### PR TITLE
568 - Create natural gas facility damage analysis

### PR DESCRIPTION
**Pull request by navarroc**
- [x] Created gas facility damage analysis
- [x] Added module documentation
- [x] Added test
- [x] Compared results with Ergo analysis output

### CODE REVIEW

**Comment by navarroc** [comment]
Here is the ergo output for comparison with the test script:
ergo-output

**Comment by navarroc** [comment]
Example notebook is in this PR for docs: https://github.com/IN-CORE/incore-docs/pull/388

**Review by longshuicy — COMMENTED** [review]
I think you might have to update the data type in that published gas facility inventory?

dataset type does not match - given type: ncsa:gasFacilityInventory spec types: ['ergo:gasFacilityInventory']
Error reading dataset: required dataset is missing - spec: {'id': 'gas_facilities', 'required': True, 'description': 'Gas facility Inventory', 'type': ['ergo:gasFacilityInventory']}

**Comment by navarroc** [comment]
> I think you might have to update the data type in that published gas facility inventory?
> 
> dataset type does not match - given type: ncsa:gasFacilityInventory spec types: ['ergo:gasFacilityInventory'] Error reading dataset: required dataset is missing - spec: {'id': 'gas_facilities', 'required': True, 'description': 'Gas facility Inventory', 'type': ['ergo:gasFacilityInventory']}

Is there an easy way to do that on dev?

**Comment by longshuicy** [comment]
> > I think you might have to update the data type in that published gas facility inventory?
> > dataset type does not match - given type: ncsa:gasFacilityInventory spec types: ['ergo:gasFacilityInventory'] Error reading dataset: required dataset is missing - spec: {'id': 'gas_facilities', 'required': True, 'description': 'Gas facility Inventory', 'type': ['ergo:gasFacilityInventory']}
> 
> Is there an easy way to do that on dev?

I can get into the mongodb and fix that tomorrow.

**Comment by navarroc** [comment]
> > > I think you might have to update the data type in that published gas facility inventory?
> > > dataset type does not match - given type: ncsa:gasFacilityInventory spec types: ['ergo:gasFacilityInventory'] Error reading dataset: required dataset is missing - spec: {'id': 'gas_facilities', 'required': True, 'description': 'Gas facility Inventory', 'type': ['ergo:gasFacilityInventory']}
> > 
> > 
> > Is there an easy way to do that on dev?
> 
> I can get into the mongodb and fix that tomorrow.

Thank you, I don't think I have all that setup to connect to mongo so I'd appreciate that.

**Review by longshuicy — APPROVED** [review]
I updated the gas facility data type to ergo:gasFacilityInventory for both dev and prod.
Code looks good and everything runs. Approving.

**Comment by ywkim312** [comment]
> Here is the ergo output for comparison with the test script: ergo-output

What should I compare to this one? I ran the test script and got 

> Here is the ergo output for comparison with the test script: ergo-output

I ran the test script and got a json file and csv file. CSV file doesn't look like the output of ergo you posted. Am I doing something wrong?
image

**Comment by navarroc** [comment]
> > Here is the ergo output for comparison with the test script: ergo-output
> 
> What should I compare to this one? I ran the test script and got a json file and csv file. CSV file doesn't look like the output of ergo you posted. Am I doing something wrong? image

Correct, because Ergo used different column naming scheme than IN-CORE. The GUID should match and then ls-slight is the same as LS_0 and so forth, None is DS_0 and so forth to compare values.

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
