### PR TITLE
493 investigate in building damage performance issue

### PR DESCRIPTION
**Pull request by longshuicy**
I realize we are looping through all the buildings redundantly. Taking out one layer of the looping when matching inventory with fragilities. Still not very fast though

Some benchmarks (before/after):

Memphis Earthquake damage run time: 4.497807025909424 
Memphis Earthquake damage run time: 3.479637861251831 

Seaside Tsunami damage run time: 12.431647062301636 
Seaside Tsunami damage run time: 11.918556928634644

Galveston Hurricane damage run time: 85.12275385856628 
Galveston Hurricane damage run time: 83.93139791488647

Lumberton Flood damage run time: 38.145187854766846
Lumberton Flood damage run time: 38.67339634895325

Joplin Tornado damage run time: 21.523848295211792
Joplin Tornado damage run time: 21.288371086120605

SLC Earthquake damage run time: 561.6372690200806
SLC Earthquake damage run time: 498.26733016967773

### CODE REVIEW

**Comment by longshuicy** [comment]
Other ways to improve include using Map Reduce/ Geopandas also have similar concept (lambda apply).

**Comment by navarroc** [comment]
From preliminary investigation, using SLC all buildings and 4 cpus on my machine, the building damage takes about 6.5 minutes to finish. Of that time, it spends just over 5 minutes in the fragility matching, about 15s requesting the hazard, about the same amount of time breaking up the data for the threads to work on (15s). The rest is some write time and computing the damage (I didn't break that out). The most inefficient part looks to be the fragility matching.

**Comment by navarroc** [comment]
I am going to run a test with liquefaction to see how much that adds to the hazard because maybe that is another area to improve if it adds a lot

**Comment by navarroc** [comment]
@longshuicy I don't see the speedup that you indicated that you saw with the changes to this branch. When I run SLC with the main branch and 4 cpus on my PC I got a runtime of about 6 minutes. Using the same input parameters with your branch here, I got a runtime of about 9 minutes. I ran both setups (main vs your branch) multiple times to make sure it wasn't a once off skewing the results. I consistently get faster speeds with the code that is in main. I'm not sure how to explain the difference.

**Comment by longshuicy** [comment]
> @longshuicy I don't see the speedup that you indicated that you saw with the changes to this branch. When I run SLC with the main branch and 4 cpus on my PC I got a runtime of about 6 minutes. Using the same input parameters with your branch here, I got a runtime of about 9 minutes. I ran both setups (main vs your branch) multiple times to make sure it wasn't a once off skewing the results. I consistently get faster speeds with the code that is in main. I'm not sure how to explain the difference.

That's before I further turned this branch into using geopandas, which actually slow down everything. If you revert one commit, you will see the similar performance as I wrote down. 
image

**Comment by longshuicy** [comment]
Closing this PR since we shall optimize in another way.

**Pull request closed without merging**
