### PR TITLE
updated buildingeconloss to handle case with no occupancy_multiplier

### PR DESCRIPTION
**Pull request by 22dylan**
[documentation](https://incore.ncsa.illinois.edu/doc/incore/analyses/building_loss.html) says occupancy_multiplier is not required. The code broke when I tried running without an occupancy multiplier file. `.get_csv_read()` on line 43 couldn't handle there being nothing. Updated to check if `occ_multiplier` is `None`. 

Additional issue on line 115 with how `"Multiplier"` was set to `1.0` in `dmg_set_df`

### CODE REVIEW

**Comment by navarroc** [comment]
@22dylan I think you should have permissions to open an issue against our pyincore github repository. Can you do this so there is an issue to track what you are fixing? Once you do that, can you update the CHANGELOG with the issue number? Thanks!

**Comment by 22dylan** [comment]
@navarroc I believe I've got this done correctly. Do I need to be worried about the 2 failed checks above?

**Comment by navarroc** [comment]
Hi @22dylan. Instead of creating a patch, can you push those changes to this branch? It's better if the commits remain together. Also, I think you can ignore the failed build checks. I believe it's because your branch doesn't include the latest from develop. None of your changes should have impacted the build. 

> @navarroc I believe I've got this done correctly. Do I need to be worried about the 2 failed checks below?

**Comment by navarroc** [comment]
Now I see the issue. You need to checkout your branch, dylan_s and push the CHANGELOG update to that branch.

**Comment by longshuicy** [comment]
Code looks good. I'm wondering why I see changes not related to this PR. Could you try merge the latest incore develop branch back into your branch to see if it can be rebased correctly? Thanks!

**Comment by 22dylan** [comment]
@longshuicy @navarroc I see in my pull request #275 only two files were changed: the CHANGELOG.md and the buildingeconloss file. Would it be easiest if I just delete this pull request and we use that one instead? #275 references the issue that I created for this (#274).

**Comment by navarroc** [comment]
> @longshuicy @navarroc I see in my pull request #275 only two files were changed: the CHANGELOG.md and the buildingeconloss file. Would it be easiest if I just delete this pull request and we use that one instead? #275 references the issue that I created for this (#274).

It's odd that the patch-1 branch only shows the files that changed. I looked at the commit history of this branch and patch-1 and they are identical from what I can tell so I don't know why the PRs look different in terms of the number of "commits" it shows and the files changed. I think you can just leave this one and we'll figure out how to review it and get it merged.

**Pull request closed without merging**
