### PR TITLE
Apply black formatter

### PR DESCRIPTION
**Pull request by ylyangtw**

### CODE REVIEW

**Review by Rashmil-1999 — APPROVED** [review]
The formatting settings seem fine to me.

**Comment by Rashmil-1999** [comment]
All the pytests run fine as well.

**Comment by Rashmil-1999** [comment]
Also can you just list what have we ignored in flake8? the ignore codes are a bit hard to understand.

**Review by longshuicy — APPROVED** [review]
Tested all relevant analysis notebooks and all works.

**Review by navarroc — APPROVED** [review]

**Pull request merged**
