### PR TITLE
365 how can post processing function handle nan value from mcs

### PR DESCRIPTION
**Pull request by longshuicy**
Just run the test and you should see it counts "NA" in the output json

### CODE REVIEW

**Comment by ywkim312** [comment]
I've got this error when running test. Is it my python environment? 
```
Exception ignored in tp_clear of: <class 'memoryview'>
Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
BufferError: memoryview has 1 exported buffer
```

**Comment by ywkim312** [comment]
I also got an error from test_dataprocessutil. 5 out of 6 were passed but galveston one got following error
```
>                   raise ValueError("cannot reindex on an axis with duplicate labels")
E                   ValueError: cannot reindex on an axis with duplicate labels

C:\venv\pyincore\lib\site-packages\pandas\core\indexes\base.py:4274: ValueError
```
I am not very sure but it might be because of my local setting?

**Comment by longshuicy** [comment]
> I've got this error when running test_buildingdamage. Is it my python environment? I've got the results jsons though
> 
> ```
> Exception ignored in tp_clear of: <class 'memoryview'>
> Traceback (most recent call last):
>   File "C:\Python310\lib\multiprocessing\reduction.py", line 51, in dumps
>     cls(buf, protocol).dump(obj)
> BufferError: memoryview has 1 exported buffer
> ```

Hmm this is related to your parallel computing multiprocessing. not sure relevant to this PR or not

**Comment by longshuicy** [comment]
> I also got an error from test_dataprocessutil. 5 out of 6 were passed but galveston one got following error
> 
> ```
> >                   raise ValueError("cannot reindex on an axis with duplicate labels")
> E                   ValueError: cannot reindex on an axis with duplicate labels
> 
> C:\venv\pyincore\lib\site-packages\pandas\core\indexes\base.py:4274: ValueError
> ```
> 
> I am not very sure but it might be because of my local setting?

fixed. could you try again

**Review by Rashmil-1999 — APPROVED** [review]

**Review by Vismayak — APPROVED** [review]

**Pull request merged**
