### PR TITLE
415 add support for local hazard in analyses

### PR DESCRIPTION
**Pull request by longshuicy**
Run the additional test and compare with legacy results

### CODE REVIEW

**Review by navarroc — APPROVED** [review]

**Comment by navarroc** [comment]
I've tested and compared the damage analyses, all look to be matching the previous results with the hazard object.

**Comment by ylyangtw** [comment]
@navarroc How do you do the tests? I have tried pytest but it gets nothing..

**Comment by ylyangtw** [comment]
Not sure whether this matters... I encounter this in test_tornadoepndamage
image
Files are generated successfully tho

**Comment by navarroc** [comment]
> @navarroc How do you do the tests? I have tried pytest but it gets nothing..

The tests Chen added all have a main function so you can run them using python test_tornadoepndamage_w_hazard_obj.py for example and then run the other test file in the tornadepndamage folder to compare with the legacy results.

**Review by ylyangtw — APPROVED** [review]
Tested all the added analyses, all work.
Also compared all the first line of csv files, all are the same.
Changes look good.

**Comment by longshuicy** [comment]
> Not sure whether this matters... I encounter this in test_tornadoepndamage image Files are generated successfully tho



> Not sure whether this matters... I encounter this in test_tornadoepndamage image Files are generated successfully tho

i created an issue will investigate later

**Comment by navarroc** [comment]
There were two issues with the unit tests failing. One was the incrtest user looks like they were over quota. I fixed that, but in doing so, I "may" have accidentally deleted a dataset it referred to when I cleaned up hazard files in the incrtest space marked as "pytest". I thought they were all created tests. I tested in a local branch and if you update test_create_hurricane_from_remote to use ID "5f11e50cc6491311a814584c", all tests should pass.

**Pull request merged**
