### PR TITLE
312 seaside joplin cge uses a fixed location for temporary files

### PR DESCRIPTION
**Pull request by ylyangtw**

### CODE REVIEW

**Comment by navarroc** [comment]
Can you update this PR to point at the release branch?

**Comment by ylyangtw** [comment]
Just changed the base branch to release-1.10.0

**Comment by navarroc** [comment]
Can you remove the import tempfile from the joplincge and seasidecge? They are no longer needed.

**Comment by ylyangtw** [comment]
> Can you remove the import tempfile from the joplincge and seasidecge? They are no longer needed.

Removed. Thanks!

**Review by navarroc — APPROVED** [review]

**Comment by Rashmil-1999** [comment]
If we are not using unique names, how did we solve this error?

**Comment by Rashmil-1999** [comment]
Perfect. It makes sense to me now. Thanks Ya-Lan.

**Review by Rashmil-1999 — APPROVED** [review]

**Pull request merged**
